[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
regex = "1"
rustc-hash = "1.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
